# Generated by Django 4.0 on 2022-11-08 22:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_user_last_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Last Location'),
        ),
    ]
