# Generated by Django 4.0 on 2022-12-11 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking', models.BooleanField(default=False, verbose_name='Tracking')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Convoy',
                'verbose_name_plural': 'Convoys',
                'ordering': ['updated'],
            },
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['verified'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterField(
            model_name='report',
            name='civilians',
            field=models.CharField(choices=[('Yes', 'Yes, there are some civilians.'), ('No', 'No, there are no civilians.'), ('Unknown', "I don't know")], default='Unknown', max_length=35, verbose_name='Civilians'),
        ),
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='report',
            name='convoy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.convoy', verbose_name='Convoy'),
        ),
    ]
